### ISSUE TITLE
Special cases: web scrapped data

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-data-library#15]
example:
```yml
dataset:
  name: &name foodbankny_foodbanks
  version: "{{ version }}"
  source:
    module: foodbankny_foodbanks
    options:
      - "AUTODETECT_TYPE=NO"
      - "EMPTY_STRING_AS_NULL=YES"
    geometry:
      SRS: EPSG:4326
      type: POINT
...
```
we will use importlib to dynamically import `module_source`
```python
import importlib
module_name = 'foodbankny_foodbanks'
module = importlib.import_module(module_name, package=None)
```
This module will have 1 function interface called `run` which will export data out via stdout. 
and gdal will ingest this data using vsistdin
https://gdal.org/user/virtual_file_systems.html#vsistdin-standard-input-streaming

if this is difficult to implement, we can just use tempfiles, we will write to tempfile, then gdal will pick up from a tempfile
