### ISSUE TITLE
Data Configuration

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-data-library#3]
for each dataset, there should be a configuration file that defines source/version/projection & etc
use jinja templating to dynamically define version info
check out the yaml files in `tests/data` to view the latest yml configurations

```yml
dataset:
  name: &name dcp_mappluto
  version: "{{ version }}"

  # Source definition
  source:
    # If source is just a url, declare like below
    url:
      # The url or local path for this data source
      path: https://www1.nyc.gov/assets/planning/download/zip/data-maps/open-data/nyc_mappluto_{{ version }}_unclipped_shp.zip
      # For zipped files, specify subpath to help gdal locate data
      subpath: nyc_mappluto_{{ version }}_unclipped/nyc_mappluto_{{ version }}.shp
    options: #srcOpenOptions
      - "AUTODETECT_TYPE=NO"
      - "EMPTY_STRING_AS_NULL=YES"
    geometry:
      srcSRS: EPSG:2263
      type: MULTIPOLYGON

  # Destination definition
  destination:
    name: *name
    geometry:
      dstSRS: EPSG:4326
      type: MULTIPOLYGON
    options: #layerCreationOptions
      - "OVERWRITE=YES"
    fields: []

    # If there's a SQL statement we would like to perform
    # @filename syntax can be used to indicate that the content 
    # is in the pointed filename.
    sql: |
      SELECT * FROM @filename LIMIT 5

  # The info field is a free formed field to include any other additional info
  info:
    # some simple description here
    description: |
      dcp_mappluto is the shoreline clipped, grabbed from bytes
      more information here, if ">" is used then it means that
      newlines are not preserved. if "|" is used then it means 
      that newline will be preserved
    # A url that doesn't lead directly to the data file but a 
    # human readable website url would be useful here
    url: https://www1.nyc.gov/site/planning/data-maps/open-data/dwn-pluto-mappluto.page
    dependents:
      - pluto_corrections
      - pluto_input_numbldgs
      - dcp_edesignation
      - dcp_colp
      - lpc_historic_districts
      - lpc_landmarks
      - dcp_cdboundaries
      - dcp_censustracts
      - dcp_censusblocks
      - dcp_school_districts
      - dcp_councildistricts
      - doitt_zipcodeboundaries
      - dcp_firecompanies
      - dcp_policeprecincts
      - dcp_healthareas
      - dcp_healthcenters
      - dsny_frequencies
      - dpr_greenthumb

      
```
### socrata sample 
```yml
dataset:
  name: &name dpr_parksproperties
  version: {{ version }}
  source:
    # if source is socrata, the url can be computed
    socrata:
      # the unique id for this dataset
      id: enfh-gkve
      # file format pulling from socrata (csv, or geojson)
      format: geojson
      options:
        - "AUTODETECT_TYPE=NO"
        - "EMPTY_STRING_AS_NULL=YES"
      geometry:
        srcSRS: EPSG:4326
        type: MULTIPOLYGON

  destination:
    name: *name
    geometry:
      dstSRS: EPSG:4326
      type: MULTIPOLYGON
    options:
      - "OVERWRITE=YES"
    fields: []

  info:
    description: |
      This dataset identifies property managed partially or solely by NYC Parks. 
      This data has been produced in whole or part using secondary data. 
      Data accuracy is limited by the scale and accuracy of the original sources. 
      Site-specific conditions should be field-verified.
      Records are added as more land is designated under NYC Parks’ jurisdiction. 
      Each record represents an acquisition.
      User Guide: https://docs.google.com/document/d/1NExNJF5YKID04oOopi0fHainRuGG3Pz_jKSrMujPsPk/edit?usp=sharing
      Data Dictionary: https://docs.google.com/spreadsheets/d/1Q4DBWu7riNFxWvy1vnTJHoOI3r2L9oW6eCN56jCNyCw/edit?usp=sharing
    url: https://data.cityofnewyork.us/Recreation/Parks-Properties/enfh-gkve

```
## sample usage:
```python
from yaml import load, dump
from jinja2 import Template

with open('example.url.yml', 'r') as f:
        template = Template(f.read())
        rendered = load(template.render(version='20v7'))

print(rendered)
```
