### ISSUE TITLE
doit_buildingfootprints script update

### ISSUE THREAD

**Issue by td928** [NYCPlanning/db-data-library#414]
Hey DE! @AmandaDoyle @damonmcc @fvankrieken  Happy Friday! Hope you are doing well.

I think I raised question about`doit_buildingfootprints` having issues with being updated

After investigating for a little bit, I found that `doit_buildingfootprints` is a little unique in that data library is not directly treating it as because it doesn't support a geojson instead `doit_buildingfootprints.py` needs to point it explicitly to the API endpoint then export it as a shapefile.  I was able to narrow the issue down to the API endpoint this line below where the endpoints are fetched from the metadata.

```python
  @property
  def uid(self):
      return self.metadata["childViews"][0]
```

But there are two endpoints, the scirpt currently is pointing stopped working and simply switched the other worked for me. See below for the change. 

```python
  @property
  def uid(self):
      return self.metadata["childViews"][1]
```

I also modified the yml template a bit for it to be more align with the data description and geometry type from the open data portal
```yaml
dataset:
  name: &name doitt_buildingfootprints
  version: "{{ version }}"
  acl: public-read
  source:
    script: *name
    options:
      - "AUTODETECT_TYPE=NO"
      - "EMPTY_STRING_AS_NULL=YES"
    geometry:
      SRS: EPSG:4269
      type: POLYGON

  destination:
    name: *name
    geometry:
      SRS: EPSG:4326
      type: POLYGON
    options:
      - "OVERWRITE=YES"
      - "PRECISION=NO"
    fields: []
    sql: null
```

Probably gonna run some more tests about this on DevDB after I finished pulling in the latest version. But I just want to flag what I find just in case you are interested. 

Best,
Te
